{{- if .Values.pdb.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget

metadata:
  name: {{ include "ping-pong.fullname" . }}

  labels:
    {{- include "ping-pong.labels" . | nindent 4 }}

spec:

  minAvailable: {{ .Values.pdb.minAvailable }}

  selector:
    matchLabels:
      {{- include "ping-pong.selectorLabels" . | nindent 6 }}

{{- end }}