apiVersion: v1
kind: Service

metadata:
  name: {{ include "ping-pong.fullname" . }}
  labels:
    {{- include "ping-pong.labels" . | nindent 4 }}

spec:
  type: {{ .Values.service.type }}

  selector:
    {{- include "ping-pong.selectorLabels" . | nindent 4 }}

  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: http